drop table "APP"."AULE"
drop table "APP"."TOKEN";
drop table "APP"."UTENTE";
drop table "APP"."TRONCO";
drop table "APP"."PDR";
drop table "APP"."NODI";
drop table "APP"."MAPPA";
drop table "APP"."BEACON";
drop table "APP"."PIANO";